-- webina-sep: the two tables rung 1 reads and rung 4 writes.
-- Generated by `python ladder.py supabase` from data/webina-sep.csv.
-- Applied once with psql (see scripts/supabase_setup.sh).

create table if not exists public.records (
  customer_id        text primary key,
  gender             text,
  senior_citizen     integer,
  partner            text,
  dependents         text,
  tenure             integer,
  phone_service      text,
  multiple_lines     text,
  internet_service   text,
  online_security    text,
  online_backup      text,
  device_protection  text,
  tech_support       text,
  streaming_tv       text,
  streaming_movies   text,
  contract           text,
  paperless_billing  text,
  payment_method     text,
  monthly_charges    numeric,
  total_charges      numeric,
  churn              text
);

-- RLS on, and an explicit read policy. With RLS on and no policy the API
-- returns zero rows and no error.
alter table public.records enable row level security;
drop policy if exists "public read" on public.records;
create policy "public read"   on public.records
  for select to anon using (true);

-- Rung 4's audit trail. The insert policy is deliberately open for the demo
-- and is said out loud on stage, not hidden.
create table if not exists public.predictions (
  id                 bigint generated always as identity primary key,
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  model_version      text,
  created_at         timestamptz default now()
);

alter table public.predictions enable row level security;
drop policy if exists "public read"   on public.predictions;
drop policy if exists "public insert" on public.predictions;
create policy "public read"   on public.predictions
  for select to anon using (true);
create policy "public insert" on public.predictions
  for insert to anon with check (true);
