"""The two tables rung 1 reads and rung 4 writes, generated from the data.

The records table's columns are whatever prepare produced, so the SQL is
written here rather than by hand. The predictions table never changes: it holds
an id, a probability, an action, a model version and a timestamp, and that is
true of every dataset this skill will ever see.

Row level security is on for both tables, with an explicit read policy. With RLS
on and no policy the API returns zero rows and no error -- the single most
expensive trap in this whole stack, so the policy is generated, never optional.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from pandas.api import types as ptypes

from .context import LadderConfig

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from insights import to_snake  # noqa: E402

RECORDS_TABLE = "records"
PREDICTIONS_TABLE = "predictions"


def sql_type(series: pd.Series) -> str:
    if ptypes.is_integer_dtype(series):
        return "integer"
    if ptypes.is_float_dtype(series):
        return "numeric"
    if ptypes.is_bool_dtype(series):
        return "boolean"
    return "text"


def generate_schema(cfg: LadderConfig, df: pd.DataFrame) -> str:
    id_column = _id_column(cfg, df)
    width = max(len(c) for c in df.columns) + 2
    lines = []
    for column in df.columns:
        kind = sql_type(df[column])
        if column == id_column:
            kind += " primary key"
        lines.append(f"  {column.ljust(width)}{kind},")
    lines[-1] = lines[-1].rstrip(",")

    return f"""-- {cfg.name}: the two tables rung 1 reads and rung 4 writes.
-- Generated by `python ladder.py supabase` from data/{cfg.name}.csv.
-- Applied once with psql (see scripts/supabase_setup.sh).

create table if not exists public.{RECORDS_TABLE} (
{chr(10).join(lines)}
);

-- RLS on, and an explicit read policy. With RLS on and no policy the API
-- returns zero rows and no error.
alter table public.{RECORDS_TABLE} enable row level security;
drop policy if exists "public read" on public.{RECORDS_TABLE};
create policy "public read"   on public.{RECORDS_TABLE}
  for select to anon using (true);

-- Rung 4's audit trail. The insert policy is deliberately open for the demo
-- and is said out loud on stage, not hidden.
create table if not exists public.{PREDICTIONS_TABLE} (
  id                 bigint generated always as identity primary key,
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  model_version      text,
  created_at         timestamptz default now()
);

alter table public.{PREDICTIONS_TABLE} enable row level security;
drop policy if exists "public read"   on public.{PREDICTIONS_TABLE};
drop policy if exists "public insert" on public.{PREDICTIONS_TABLE};
create policy "public read"   on public.{PREDICTIONS_TABLE}
  for select to anon using (true);
create policy "public insert" on public.{PREDICTIONS_TABLE}
  for insert to anon with check (true);
"""


def write_schema(cfg: LadderConfig, df: pd.DataFrame) -> Path:
    path = cfg.root / "supabase" / "schema.sql"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_schema(cfg, df), encoding="utf-8")
    return path


def _id_column(cfg: LadderConfig, df: pd.DataFrame) -> str:
    candidate = to_snake(cfg.id_column) if cfg.id_column else "row_id"
    return candidate if candidate in df.columns else df.columns[0]
